AWSTemplateFormatVersion: '2010-09-09'
Description: |
  X-Ray Watch POC - IAM Roles Template
  ECS Task Execution Role, Task Role, GitHub Actions Role
  Version: 1.0.0

Parameters:
  Environment:
    Type: String
    Description: Environment name

  GitHubOrg:
    Type: String
    Default: k-tanaka-522
    Description: GitHub organization name

  GitHubRepo:
    Type: String
    Default: AWSDevOpsAgentSample
    Description: GitHub repository name

Resources:
  # ==============================================================================
  # ECS Task Execution Role
  # ==============================================================================
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ecs-task-execution-role
        - Key: Environment
          Value: !Ref Environment

  EcsTaskExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Environment}-ecs-task-execution-policy
      Roles:
        - !Ref EcsTaskExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SecretsManagerAccess
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:xray-poc/*

  # ==============================================================================
  # ECS Task Role
  # ==============================================================================
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-ecs-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ecs-task-role
        - Key: Environment
          Value: !Ref Environment

  EcsTaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Environment}-ecs-task-policy
      Roles:
        - !Ref EcsTaskRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: XRayAccess
            Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: '*'
          - Sid: CloudWatchAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - cloudwatch:PutMetricData
            Resource: '*'
          - Sid: RDSAccess
            Effect: Allow
            Action:
              - rds-db:connect
            Resource: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/app_user

  # ==============================================================================
  # GitHub OIDC Provider
  # ==============================================================================
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-github-oidc
        - Key: Environment
          Value: !Ref Environment

  # ==============================================================================
  # GitHub Actions Role
  # ==============================================================================
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:*
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-github-actions-role
        - Key: Environment
          Value: !Ref Environment

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${Environment}-github-actions-policy
      Roles:
        - !Ref GitHubActionsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ECRPushAccess
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
            Resource: '*'
          - Sid: ECSDeployAccess
            Effect: Allow
            Action:
              - ecs:UpdateService
              - ecs:DescribeServices
              - ecs:DescribeTaskDefinition
              - ecs:RegisterTaskDefinition
            Resource: '*'
          - Sid: PassRoleToECS
            Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !GetAtt EcsTaskExecutionRole.Arn
              - !GetAtt EcsTaskRole.Arn

Outputs:
  EcsTaskExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt EcsTaskExecutionRole.Arn

  EcsTaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt EcsTaskRole.Arn

  GitHubActionsRoleArn:
    Description: GitHub Actions Role ARN
    Value: !GetAtt GitHubActionsRole.Arn
