AWSTemplateFormatVersion: '2010-09-09'
Description: |
  X-Ray Watch POC - Monitoring Stack (04-monitoring)
  CloudWatch Alarms, SNS Topic, X-Ray Configuration
  Version: 1.0.0
  Last Updated: 2025-12-10

Metadata:
  Version: 1.0.0
  Author: SRE Team
  ChangeLog:
    - '2025-12-10: Initial release'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - development
    Description: Environment name

  DatabaseStackName:
    Type: String
    Default: xray-poc-database
    Description: Database Stack name

  ComputeStackName:
    Type: String
    Default: xray-poc-compute
    Description: Compute Stack name

  AlertEmail:
    Type: String
    Description: Email address for alert notifications
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

Resources:
  # ==============================================================================
  # SNS Topic
  # ==============================================================================
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-alerts
      DisplayName: X-Ray POC Alerts
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-sns-topic
        - Key: Environment
          Value: !Ref Environment

  SnsTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SnsTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  # ==============================================================================
  # ALB Alarms
  # ==============================================================================
  AlbTargetResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-alb-target-response-time
      AlarmDescription: ALB target response time is too high
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 0.5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Select
            - 1
            - !Split
              - 'loadbalancer/'
              - Fn::ImportValue: !Sub ${ComputeStackName}-AlbArn
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  AlbTarget5xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-alb-target-5xx-error
      AlarmDescription: ALB target 5xx errors are too high
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Select
            - 1
            - !Split
              - 'loadbalancer/'
              - Fn::ImportValue: !Sub ${ComputeStackName}-AlbArn
        - Name: TargetGroup
          Value: !Select
            - 1
            - !Split
              - 'targetgroup/'
              - Fn::ImportValue: !Sub ${ComputeStackName}-TargetGroupArn
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  AlbHealthyHostCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-alb-healthy-host-count
      AlarmDescription: No healthy hosts available
      MetricName: HealthyHostCount
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Select
            - 1
            - !Split
              - 'loadbalancer/'
              - Fn::ImportValue: !Sub ${ComputeStackName}-AlbArn
        - Name: TargetGroup
          Value: !Select
            - 1
            - !Split
              - 'targetgroup/'
              - Fn::ImportValue: !Sub ${ComputeStackName}-TargetGroupArn
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: breaching

  # ==============================================================================
  # ECS Alarms
  # ==============================================================================
  EcsCpuUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-ecs-cpu-utilization
      AlarmDescription: ECS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsClusterName
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsServiceName
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  EcsMemoryUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-ecs-memory-utilization
      AlarmDescription: ECS memory utilization is too high
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsClusterName
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsServiceName
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  EcsRunningTasksCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-ecs-running-tasks-count
      AlarmDescription: ECS running tasks count is less than desired
      MetricName: RunningTaskCount
      Namespace: ECS/ContainerInsights
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClusterName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsClusterName
        - Name: ServiceName
          Value:
            Fn::ImportValue: !Sub ${ComputeStackName}-EcsServiceName
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: breaching

  # ==============================================================================
  # RDS Alarms
  # ==============================================================================
  RdsCpuUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-rds-cpu-utilization
      AlarmDescription: RDS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::ImportValue: !Sub ${DatabaseStackName}-DBInstanceIdentifier
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  RdsFreeableMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-rds-freeable-memory
      AlarmDescription: RDS freeable memory is too low
      MetricName: FreeableMemory
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 209715200
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::ImportValue: !Sub ${DatabaseStackName}-DBInstanceIdentifier
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

  RdsFreeStorageSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-rds-free-storage-space
      AlarmDescription: RDS free storage space is too low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 2147483648
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value:
            Fn::ImportValue: !Sub ${DatabaseStackName}-DBInstanceIdentifier
      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopic
      TreatMissingData: notBreaching

Outputs:
  SnsTopicArn:
    Description: SNS Topic ARN for Alerts
    Value: !Ref SnsTopic
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopicArn
